---
input_select:
  water_supply_mode:
    name: Water Supply Mode
    options:
    - "MODE_RUNNING: 1"
    - "MODE_MANUAL_OVERRIDE: 2"
    - "MODE_CALIBRATION: 3"
    - "MODE_WATER_SUPPLY_ERROR: 4"

pyscript:


#automation:
#- alias: "Set Water Supply Mode Selector"
#  trigger:
#    platform: state
#    entity_id: sensor.water_supply_01_mode
#  action:

var:
  water_supply_mode_entities:
    friendly_name: 'Water Supply Mode Entities'
  seedship_drainage_entities:
    friendly_name: 'SeedShip Drainage Entities'
  seedship_water_nozzle_entities:
    friendly_name: 'SeedShip Water Nozzle Entities'

  lists_of_entities:
    friendly_name: 'Lists of Entities'

lovelace:
  dashboards:
    lovelace-seedship:
      mode: yaml
      title: SeedShips
      icon: mdi:script
      show_in_sidebar: true
      filename: dashboards/seedships.yaml
